- name: Demo Playbook
  hosts: web
  remote_user: ubuntu
  gather_facts: false
  # become: true
  # become_user: root
  # become_method: sudo

  vars:
    ansible_host_key_checking: false
    ansible_python_interpreter: /usr/bin/python3
    ansible_stdout_callback: yaml

  pre_tasks:
    - name: Check targets connectivity
      wait_for_connection:
        connect_timeout: 5
        timeout: 60

    - name: Install python3 for ansible
      become: true
      apt:
        name: python3
        update_cache: yes

  roles:
    - install_nodejs
    - deploy
